feature(setup) Setup project and add color palette
tomuhenry/JavaDevs pull request #3
Opened 2019-03-25 07:54 UTC by tomuhenry

**Description of tasks to be completed**
- Go to www.materialpalette.com
- Add color palatte
- Add circleci badge
- Add code climate badge
- Setup the android project
- Add badges

**Relevant Pivotal Tracker stories**
[#159051218](https://www.pivotaltracker.com/story/show/159051218)
[#155738437](https://www.pivotaltracker.com/story/show/155738437)
[#155738456](https://www.pivotaltracker.com/story/show/155738456)
[#155738450](https://www.pivotaltracker.com/story/show/155738450)

Old Color Scheme
<img width="321" alt="Screen Shot 2019-03-21 at 3 43 25 PM" src="https://user-images.githubusercontent.com/40206038/54902895-91afa800-4eeb-11e9-8d4c-b3dc1a633ee4.png">

Color Palatte
![palette](https://user-images.githubusercontent.com/40206038/54903047-ff5bd400-4eeb-11e9-8e81-0819614eeb0b.png)

New Color Scheme
<img width="322" alt="Screen Shot 2019-03-21 at 3 45 38 PM" src="https://user-images.githubusercontent.com/40206038/54902901-94aa9880-4eeb-11e9-8252-f07b262a9733.png">

2019-03-25 08:13 UTC, tomuhenry commented
Hey @damafeez, the badges are pointing to the **develop** branch and that is why the build is failing. But the might will be able to solve that.

2019-03-25 09:29 UTC, damafeez requested changes
Good job @tomuhenry. This PR contains some files you don't directly interact with, however. You can add these paths to your `.gitignore`
```
*.iml
.gradle
/local.properties
/.idea/caches/build_file_checksums.ser
/.idea/libraries
/.idea/modules.xml
/.idea/workspace.xml
.DS_Store
/build
/captures
.externalNativeBuild
```

2019-03-25 09:29 UTC, damafeez commented on .idea/libraries/Gradle__android_arch_core_common_1_1_1_jar.xml
> +<component name="libraryTable">
You don't interact directly with files in the `/.idea/libraries` path, you ignore them.
You can add `/.idea/libraries` to your `.gitignore`

2019-03-25 10:08 UTC, tomuhenry commented on .idea/libraries/Gradle__android_arch_core_common_1_1_1_jar.xml
> +<component name="libraryTable">
Added the files to the `.gitignore file`

2019-03-26 09:22 UTC, damafeez approved these changes
LGTM, I'm merging this

2019-03-26 09:22 UTC, merged