#155931587 Create DetailActivity, retrofit and Access API
tomuhenry/JavaDevs pull request #5
Opened 2019-04-10 11:19 UTC by tomuhenry

**What does this PR do?**
This PR handles DetailActivity file, retrofit, and accessing API

**Description of Task to be completed?**
- Create layout file for DetailActivity and launch it through MainActivity
- Implement retrofit
- Access the [Github API](https://api.github.com/search/users?q=location:Nairobi+language:Java)

**What are the relevant Pivotal Tracker stories?**
[#155820624](https://www.pivotaltracker.com/story/show/155820624)
[#155820645](https://www.pivotaltracker.com/story/show/155820645)
[#155810744](https://www.pivotaltracker.com/story/show/155810744) 
[#155810847](https://www.pivotaltracker.com/story/show/155810847)

<img width="321" alt="Screen Shot 2019-04-10 at 2 13 47 PM" src="https://user-images.githubusercontent.com/40206038/55874426-06950a00-5b9b-11e9-8ab7-236eb2f3da67.png">
<img width="321" alt="Screen Shot 2019-04-10 at 2 14 24 PM" src="https://user-images.githubusercontent.com/40206038/55874429-098ffa80-5b9b-11e9-9e96-aff05572f1e1.png">
<img width="320" alt="Screen Shot 2019-04-10 at 2 16 01 PM" src="https://user-images.githubusercontent.com/40206038/55874521-49ef7880-5b9b-11e9-9316-38a0ace44374.png">
<img width="320" alt="Screen Shot 2019-04-10 at 2 16 31 PM" src="https://user-images.githubusercontent.com/40206038/55874542-54aa0d80-5b9b-11e9-8ee7-bf3683aa9e55.png">

2019-04-10 11:29 UTC, tomuhenry commented
Hey @bibangamba, Could you please help with some reviews for this PR
Thanks.

2019-04-10 12:30 UTC, bibangamba requested changes
the core implementation looks good @tomuhenry, but you have a lot of convention issues and code structuring issues. please fix them.

2019-04-10 12:30 UTC, bibangamba commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/MainActivity.java
> +        swipeContainer.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
please remove this implementation of the swipe to refresh layout as it is a deliverable you'll give in the UI/UX revamp later on

2019-04-10 12:30 UTC, bibangamba commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/MainActivity.java
> +                    Log.d("Error", t.getMessage());
please remove all `Logs` as well as their import statements

2019-04-10 12:30 UTC, bibangamba commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/ItemAdapter.java
> +//import android.content.Context;
please remove this whole block comment as you don't need it. please ensure that you remove all the other single line comments in your code. I've seen quite a number

2019-04-10 12:30 UTC, bibangamba commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/DetailActivity.java
> +        Linkify.addLinks(Link, Linkify.WEB_URLS);
very nice!!

2019-04-10 12:30 UTC, bibangamba commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/model/ItemResponse.java
> +public class ItemResponse {
This name (`ItemResponse`) feels very generic. please change it to something that would make it easy for anyone to understand what the Class represents/is/does - [clean code](https://medium.com/mindorks/meaningful-names-a-dimension-of-writing-clean-code-fdae1ae4f0b1).

2019-04-10 12:30 UTC, bibangamba commented on app/src/main/res/menu/detail.xml
> +<?xml version="1.0" encoding="utf-8"?>
please rename this file so it shows its meaning immediately. something like `share_menu` would have been easier to understand

2019-04-10 12:30 UTC, bibangamba commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/model/Item.java
> +public class Item {
please rename this class to show what it does/represents

2019-04-10 12:30 UTC, bibangamba commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/MainActivity.java
> +        try{
this whole block should not be happening in the `MainActivity` class. you're not following the MVP pattern in this example. It should be moved into a presenter. this [link](https://github.com/jeancsanchez/Simple-MVP-Retrofit-example) shows an example of how you can partially implement the MVP architecture (although it is not perfect & will have to be improved when working on your D2 advancement outputs)

2019-04-10 12:30 UTC, bibangamba commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/MainActivity.java
> +    ProgressDialog pd;
please use meaningful names in your code. `pd` is meaningless to anyone new to your code base. ensure to clean up most instances of this (`meaningful naming of variable, methods, classes, etc`) in your codebase

2019-04-10 14:03 UTC, tomuhenry commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/model/Item.java
> +public class Item {
Done

2019-04-10 14:03 UTC, tomuhenry commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/MainActivity.java
> +        try{
Noted... Thanks. Gonna Refactor that.

2019-04-10 14:03 UTC, tomuhenry commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/DetailActivity.java
> +        Linkify.addLinks(Link, Linkify.WEB_URLS);
Thanks

2019-04-10 14:03 UTC, tomuhenry commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/MainActivity.java
> +                    Log.d("Error", t.getMessage());
Done

2019-04-10 14:03 UTC, tomuhenry commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/MainActivity.java
> +        swipeContainer.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
Ok... Removed

2019-04-11 09:51 UTC, tomuhenry commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/controller/MainActivity.java
> +    ProgressDialog pd;
Done

2019-04-16 10:29 UTC, bibangamba approved these changes
LGTM. I've left some comments on some minor (but important) things I'd like you to change. please look into changing them in the next PR since we are quite behind.

I'm going to merge this in.

2019-04-16 10:29 UTC, bibangamba commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/adapter/GithubUserAdapter.java
> +                        Toast.makeText(v.getContext(), "You clicked " + clickedDataUserDetail.getUserName(), Toast.LENGTH_SHORT).show();
please ensure to remove this in the next PR

2019-04-16 10:29 UTC, bibangamba commented on app/src/main/res/menu/detail.xml
> +<?xml version="1.0" encoding="utf-8"?>
please rename this file in the next PR as well. `detail.xml` doesn't really convey the fact that it is a share menu. it doesn't convey anything really...

2019-04-16 10:32 UTC, merged

2019-04-16 11:14 UTC, tomuhenry commented on app/src/main/java/com/andela/tomusange/javadevsnairobi/view/adapter/GithubUserAdapter.java
> +                        Toast.makeText(v.getContext(), "You clicked " + clickedDataUserDetail.getUserName(), Toast.LENGTH_SHORT).show();
I've removed the Toast

2019-04-16 11:14 UTC, tomuhenry commented on app/src/main/res/menu/detail.xml
> +<?xml version="1.0" encoding="utf-8"?>
Renamed to `share_menu.xml`